kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-local
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 223Gi
  volumeName: local-pv-5ebe93a
  storageClassName: local-sc
  volumeMode: Filesystem
