unclassified:
  globalLibraries:
    libraries:
      - name: coreos
        defaultVersion: master
        implicit: false
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/coreos/coreos-ci-lib.git"
